### ISSUE TITLE
Huge Gap

### ISSUE THREAD

**Issue by snoazll** [SoapyHamHocks/MetroSteamSettings#10]
There's a huge gap in the exact area where your "Time Played" statistics and "Play Button" is, since the 4.0 release, on Linux. - Problem does not exist on Windows.

It's a Gnome on Arch, but I've encountered the same problem on KDE and MATE, too. - Changed the fonts, didn't work.

![gap](https://cloud.githubusercontent.com/assets/7672092/10119351/4f98acce-6483-11e5-96c9-b7414b207015.png)

**Comment by gouglhupf** [comment]
I have the same problem but it only occurs when it is available on Linux. So maybe the button causes this gap. Please fix!

**Comment by gouglhupf** [comment]
I found the issue. This thing is probably an error for steam. It occurs when the skin hides the text of Launch / Install.. Button which is normally there. The key is to set all "font-size" to something greater when zero, it doesn't matter which number because it is hidden anyway. Replace the file "gamespage_details_subheader.layout" in "~.steam/skins/Metro for Steam/resource/layout" with my file or just replace all "font-size=0" in the file with "font-size=5".

[metroforsteam_fix_huge_gap.zip](https://github.com/SoapyHamHocks/MetroSteamSettings/files/65630/metroforsteam_fix_huge_gap.zip)

**Comment by snoazll** [comment]
Sorry, it's been a while.

Thank you, so much, for investigating this issue. I actually gave up on it, because there's been a while since they've released a new version. But your workaround works like a charm!
